name: 04GitOps  github action to find tabs in code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  prepare:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Get changed files
          id: changed-files
          uses: tj-actions/changed-files@v35
        - name: Found tabs in the files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          echo "File $file content `grep '\t' $file | wc -l` TAB" >> tab_report.log 2>&1


      - name: Upload the report
        uses: actions/upload-artifact@v2
        with:
          path: tab_report.log

